repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]

  # - repo: https://github.com/myint/autoflake
  #   rev: v1.5
  #   hooks:
  #     - id: autoflake
  #       args: [
  #         "--remove-all-unused-imports",
  #         "--remove-unused-variables",
  #         "--in-place",
  #         "--recursive",
  #         "src"
  #       ]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
